### PR TITLE
feat: output json

### LINKED ISSUE #173: JSON metadata export
Thanks for this library + service! It is wonderful!

**Goal**

On gradio we publish a large number of packages and the comment is very noisy, even with the current accordion implementation. We also have a number of other comments that are generated as part of our CI process.

It would be great if we could could have some more control over the the comment created.

**Proposed solution**

While it may be possible to make the comment configurable, i think this will probably just result in a seemingly infinite loop of tweaks and options.

I think the best solution would be to export some metadata for the previews, so that users can do what they want with it. I think it is unreasonable to print this to stdout via the CLI due to the long length of the data, saving it to a json file seems most appropriate.

I think this would be great:

```
pnpx pkg-pr-new publish --json
```

This would save the meatadata to a json file (`pkg-pr-new.json` or something)

We could also allow users to set the file path:

```
pnpx pkg-pr-new publish --json=path/file.json
```

**Metadata structure**

For forwards compatibility reasons, i think it would make sense to have a json object with a `publishedPackages` key, rather than a plain json array. 

The packages themselves only need to list the `name` and the two preview links that are generated (i think `pkg.pr.new` generates both a PR suffix and a sha shorthash prefix version of the urls?). So something like this:

```ts
interface Package {
  name: string;
  sha_url: string;
  pr_url: string;
  template: string
}

interface Metadata {
  workflow_url: string; // url to the pkg.pr.new. workflow
  publishedPackages: Package[]

  // we could add additional metadata if needed
  // such as the commit sha, pr number, repo, etc
}
```

I like this approach because it should work well with some of the other proposed changes, would only tell you about new publishes (rather than the contents of your workspace), and should be flexible enough so that more information could be added in the future. It also gives the user plenty of flexibility without placing a huge maintenance burden on this library.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #173

### CODE REVIEW

**Comment by Aslemammad** [comment]
@pngwn Can you try this in your workflow and see if --json works as expected for you?

```yml
        run: API_URL=https://pkg.pr.new pnpx pkg-pr-new@https://d61368b4.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@183 publish './js/*' './client/js' --comment=off
```

You can just try different variations of `--json` on this command.

**Comment by pngwn** [comment]
I shall try!

**Comment by pngwn** [comment]
Works beautifully for stdout: https://github.com/gradio-app/gradio/actions/runs/10469032256/job/28991194562?pr=9153#step:5:150
And so does the JSON file option: https://github.com/gradio-app/gradio/actions/runs/10469152056/job/28991538458?pr=915


Thank youuuuuuuuu!

One question, it is also possible to install via `link@pr` number, would that still work?

**Comment by Aslemammad** [comment]
Thank you so much, yes it'd be possible but I did not put it in the
metadata because you can easily access the pr number from github
environment vars.

So you can construct the pr url easily for yourself.

Let me know if you have any questions, and if this can be merged ❤️

**Comment by pngwn** [comment]
That's great thanks!

Yep this looks perfect to merge from my end!

**Comment by Aslemammad** [comment]
Thank you so much!

**Review by AmirSa12 — APPROVED** [review]

**Pull request merged**
