### PR TITLE
doc: Add 47ng to list of users

### PR DESCRIPTION
**Pull request by franky47**
I've just integrated it in `nuqs`, where I already had a manual snapshot release workflow, but which "polluted" the NPM registry. This is miles better for preview versions.

Workflow: https://github.com/47ng/nuqs/blob/next/.github/workflows/pkg.pr.new.yml

### CODE REVIEW

**Review by Aslemammad — APPROVED** [review]
Thank you so much!

**Comment by Aslemammad** [comment]
Oh sorry, this is a username, we cannot add that! 

Does `nuqs` has a logo itself or maybe a text that we can add?

**Comment by franky47** [comment]
Yes I can change it to the nuqs wordmark. 47ng is the OSS org under which I publish all my work (like TanStack for Tanner Linsley).

**Comment by Aslemammad** [comment]
Yep, that'd work!

**Comment by franky47** [comment]
Hum the wordmark takes a lot of space if set to 40px height like other items, what do you think?

CleanShot 2024-09-03 at 11 37 34@2x


Otherwise, I can use the favicon:

CleanShot 2024-09-03 at 11 37 05@2x

**Comment by Aslemammad** [comment]
The favicon is amazing!

**Pull request merged**
